### PR TITLE
Add NanookRest

### PR DESCRIPTION
**Pull request by emag**
Add NanookRest. these api content is just mock.

### CODE REVIEW

**Comment by eprogramming** [comment]
Cool !

**Comment by eprogramming** [comment]
now we have static + servlet +  jax-rs working great !
do you have some ideas with EJB timer ? : D 
maybe in a soon future...

**Comment by emag** [comment]
> do you have some ideas with EJB timer ? : D 
> maybe in a soon future...

Unfortunately, now WF-Swarm is [not supported EJB](https://github.com/wildfly-swarm/wildfly-swarm/issues/59).

And Nanook + EJB Timer ? Hmm, I can't come up with usecase for now. Do you have any ideas?

**Comment by eprogramming** [comment]
Maybe since we are running commands , maybe we can try todo behavior like 'crontab' : D
to run commands from time to time ... wdyt ?

for instance a EJB timer to run **ls** command 5 and 5 minutes

**Comment by emag** [comment]
Yeah, sounds good. It needs server push(like WebSockets, Server-Sent Events) ?

**Comment by eprogramming** [comment]
we need just an idea to try

**Comment by emag** [comment]
I filed it. #126

**Comment by eprogramming** [comment]
cool !

**Pull request merged**
